USE [master]
GO
/****** Object:  Database [ThesisManagementDB]    Script Date: 19/03/2025 8:28:17 SA ******/
CREATE DATABASE [ThesisManagementDB]
 
GO
ALTER DATABASE [ThesisManagementDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ThesisManagementDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ThesisManagementDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ThesisManagementDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ThesisManagementDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ThesisManagementDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ThesisManagementDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ThesisManagementDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ThesisManagementDB] SET  MULTI_USER 
GO
ALTER DATABASE [ThesisManagementDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ThesisManagementDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ThesisManagementDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ThesisManagementDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ThesisManagementDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ThesisManagementDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ThesisManagementDB] SET QUERY_STORE = OFF
GO
USE [ThesisManagementDB]
GO
/****** Object:  Table [dbo].[GiangVien]    Script Date: 19/03/2025 8:28:17 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GiangVien](
	[GiangVienID] [int] IDENTITY(1,1) NOT NULL,
	[HoTen] [nvarchar](100) NOT NULL,
	[MaGiangVien] [nvarchar](20) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[SoDienThoai] [nvarchar](15) NULL,
	[BoMon] [nvarchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[GiangVienID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[MaGiangVien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SinhVien]    Script Date: 19/03/2025 8:28:17 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SinhVien](
	[SinhVienID] [int] IDENTITY(1,1) NOT NULL,
	[HoTen] [nvarchar](100) NOT NULL,
	[MaSinhVien] [nvarchar](20) NOT NULL,
	[Lop] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SinhVienID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[MaSinhVien] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SinhVienGiangVienHuongDan]    Script Date: 19/03/2025 8:28:17 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SinhVienGiangVienHuongDan](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SinhVienID] [int] NOT NULL,
	[GiangVienID] [int] NOT NULL,
	[NgayBatDau] [date] NOT NULL,
	[GhiChu] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 19/03/2025 8:28:17 SA ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](100) NOT NULL,
	[PasswordHash] [nvarchar](255) NOT NULL,
	[Email] [nvarchar](100) NOT NULL,
	[Role] [nvarchar](50) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SinhVienGiangVienHuongDan] ADD  DEFAULT (getdate()) FOR [NgayBatDau]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO
ALTER TABLE [dbo].[Users] ADD  DEFAULT (CONVERT([bit],(1))) FOR [IsActive]
GO
ALTER TABLE [dbo].[SinhVienGiangVienHuongDan]  WITH CHECK ADD FOREIGN KEY([GiangVienID])
REFERENCES [dbo].[GiangVien] ([GiangVienID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SinhVienGiangVienHuongDan]  WITH CHECK ADD FOREIGN KEY([SinhVienID])
REFERENCES [dbo].[SinhVien] ([SinhVienID])
ON DELETE CASCADE
GO
USE [master]
GO
ALTER DATABASE [ThesisManagementDB] SET  READ_WRITE 
GO
